### PR TITLE
Update ath9k CSCA/CA (collision avoidance) params

### PR DESCRIPTION
**Pull request by htcohio**
Reverting ath9k CA settings back to more "friendly" settings in order to improve stability / Reduce bad blocks with other wifi traffic around.

Alternatively, in very noisy wifi environments, the following settings can be used instead as the "not friendly" way of simply "stepping over" other wifi traffic.  These settings can also increase video bitrate by 10-20% at the expense of possible packet loss/bad blocks.

options ath9k_hw txpower=58 aifs=0 cwmin=0 cwmax=0 cck_sifs=10 ofdm_sifs=16 slottime=3 thresh62=38

### CODE REVIEW

**Comment by pilotnbr1** [comment]
Do you really mean to roll these 10+ file commits into one commit? It’s a lot of changes some with conflicts- is it an error?

**Comment by pilotnbr1** [comment]
I think the problem is that it’s taking your master branch and now trying to apply it to dev branch. Going backwards maybe. I didn’t open all or investigate closely

**Comment by htcohio** [comment]
Oh, No it was just 1 line in Ath9k_fw driver.... I will resubmit...

**Comment by htcohio** [comment]
Luke,

PR #42 that you approved was all we needed.

This #32 is no longer needed please ignore/disregard.

**Pull request closed without merging**
